version: '3.7'
services:
  adguardhome:
    image: adguard/adguardhome:latest
    volumes:
      - /mnt/docker-volumes/adguardhome-work:/opt/adguardhome/work
      - /mnt/docker-volumes/adguardhome-conf:/opt/adguardhome/conf
    restart: always
    ports:
      - target: 53
        published: 53
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
      - target: 68
        published: 68
        protocol: udp
        mode: host
      - target: 80
        published: 280
        mode: host
      - target: 443
        published: 2443
        mode: host
      - target: 443
        published: 2443
        protocol: udp
        mode: host
      - target: 3000
        published: 23000
        mode: host
      - target: 853
        published: 853
        mode: host
      - target: 784
        published: 784
        protocol: udp
        mode: host
      - target: 853
        published: 853
        protocol: udp
        mode: host
      - target: 8853
        published: 8853
        protocol: udp
        mode: host
      - target: 5443
        published: 5443
        mode: host
      - target: 5443
        published: 5443
        protocol: udp
        mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.adguard-secure.rule=Host(`adguard.louisa.uno`)"
      - "traefik.http.routers.adguard-secure.entrypoints=websecure"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.services.adguard-secure.loadbalancer.server.port=80"
    networks:
      - traefik-public
    cpu_shares: 2048
networks:
  traefik-public:
    external: true
