version: '3.7'
services:
  adguardhome:
    image: adguard/adguardhome:latest
    volumes:
      - /mnt/docker-volumes/adguardhome-work:/opt/adguardhome/work
      - /mnt/docker-volumes/adguardhome-conf:/opt/adguardhome/conf
      - /mnt/docker-volumes/traefik-certs:/certs:ro
    restart: always
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 443
        published: 2443
        protocol: tcp
        mode: host
    networks:
      - traefik-public
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 200M
networks:
  traefik-public:
    external: true
