version: '3.7'
services:
  adguardhome:
    image: adguard/adguardhome:latest
    volumes:
      - /mnt/docker-volumes/adguardhome-work:/opt/adguardhome/work
      - /mnt/docker-volumes/adguardhome-conf:/opt/adguardhome/conf
    restart: always
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 67
        published: 67
        protocol: udp
        mode: host
      - target: 68
        published: 68
        protocol: udp
        mode: host
      - target: 80
        published: 280
        protocol: tcp
        mode: host
      - target: 443
        published: 2443
        protocol: tcp
        mode: host
      - target: 443
        published: 2443
        protocol: udp
        mode: host
      - target: 3000
        published: 23000
        protocol: tcp
        mode: host
      - target: 853
        published: 853
        protocol: tcp
        mode: host
      - target: 784
        published: 784
        protocol: udp
        mode: host
      - target: 853
        published: 853
        protocol: udp
        mode: host
      - target: 8853
        published: 8853
        protocol: udp
        mode: host
      - target: 5443
        published: 5443
        protocol: tcp
        mode: host
      - target: 5443
        published: 5443
        protocol: udp
        mode: host
    networks:
      - default
