version: '3.7'
services:
  adguardhome:
    image: adguard/adguardhome:latest
    volumes:
      - /mnt/raid1/docker-volumes/adguardhome-work:/opt/adguardhome/work
      - /mnt/raid1/docker-volumes/adguardhome-conf:/opt/adguardhome/conf
    restart: always
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - 67:67/udp
      - 68:68/udp
      - 280:80/tcp
      - 2443:443/tcp
      - 2443:443/udp
      - 23000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    networks:
      - default
networks:
  default:
    driver: overlay
    attachable: true
