version: '3.7'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - /mnt/docker-volumes/vaultwarden-data:/data/
    restart: always
    ports:
    - target: 80
      published: 480
      mode: host
