version: '3.7'
services:
  claim-free-steam-packages:
    image: ghcr.io/luois45/claim-free-steam-packages:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 0
    volumes:
      # Replace the first path with your path to the activated_packages.txt & config.json file
      - /mnt/docker-volumes/claim-free-steam-packages/activated_packages.txt:/usr/src/app/activated_packages.txt
      - /mnt/docker-volumes/claim-free-steam-packages/config.json:/usr/src/app/config.json
      # Comment the following line if you don't want the logs in your directory
      - /mnt/docker-volumes/claim-free-steam-packages/logging.txt:/usr/src/app/logging.txt
