version: '3.7'
services:
  archisteamfarm:
    image: justarchi/archisteamfarm
    volumes:
      - /mnt/docker-volumes/archisteamfarm-config:/app/config
    restart: unless-stopped
    ports:
    - target: 1242
      published: 21242
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.archisteamfarm.rule=Host(`asf.louisa.uno`)"
    networks:
      - traefik-public
  claim-free-steam-packages:
    image: luois45/claim-free-steam-packages
    restart: unless-stopped
    depends_on:
      - archisteamfarm
    volumes:
      # Replace the first path with your path to the activated_packages.txt & config.json file
      - /mnt/docker-volumes/claim-free-steam-packages/activated_packages.txt:/usr/src/app/activated_packages.txt
      - /mnt/docker-volumes/claim-free-steam-packages/config.json:/usr/src/app/config.json:ro
      # Comment the following line if you don't want the logs in your directory
      - /mnt/docker-volumes/claim-free-steam-packages/logging.txt:/usr/src/app/logging.txt
networks:
  traefik-public:
    external: true
