version: '3.7'
services:
  dashdot:
    image: mauricenino/dashdot
    volumes:
      - /:/mnt/host:ro
    ports:
      - 3301:3001
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_USE_IMPERIAL=false
      - DASHDOT_ACCEPT_OOKLA_EULA=true
      - DASHDOT_USE_NETWORK_INTERFACE=enp6s0
      - DASHDOT_FS_VIRTUAL_MOUNTS=/mnt/raid1
