version: '3.7'
services:
  dashdot:
    image: mauricenino/dashdot
    volumes:
      - /:/mnt/host:ro
    ports:
    - target: 3001
      published: 3301
      mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_USE_IMPERIAL=false
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
