version: '3.7'
services:
  dashdot:
    image: mauricenino/dashdot
    volumes:
      - /:/mnt/host:ro
    ports:
    - target: 3001
      published: 3301
      mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - DASHDOT_SHOW_HOST=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_ENABLE_STORAGE_SPLIT_VIEW=true
      - DASHDOT_USE_IMPERIAL=false
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.dashdot.rule=Host(`dashdot.louis45.de`)"
      - "traefik.http.routers.dashdot.entrypoints=websecure"
      - "traefik.http.routers.dashdot.tls=true"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
