version: '3.7'
services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 8080
      published: 48080
      mode: host
    restart: unless-stopped
    environment:
      DOZZLE_LEVEL: trace
      DOZZLE_USERNAME: admin
      DOZZLE_PASSWORD: !!!CENSORED!!!
      DOZZLE_NO_ANALYTICS: 1
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.dozzle-secure.rule=Host(`dozzle.louis45.de`)"
      - "traefik.http.routers.dozzle-secure.entrypoints=websecure"
      - "traefik.http.routers.dozzle-secure.tls=true"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
