version: '3.7'
services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 8080
      published: 48080
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.louisa.uno`)"
    restart: unless-stopped
    environment:
      DOZZLE_LEVEL: trace
      DOZZLE_NO_ANALYTICS: 1
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
