version: "3.7"
services:
  epicgames-freegames:
    image: charlocharlie/epicgames-freegames:latest
    container_name: epicgames-freegames
    volumes:
      - /mnt/raid1/docker/volumes/epicgames-freegames-config:/usr/app/config
    ports:
      - 3000:3000
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
