version: '3.7'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /mnt/raid1/docker/volumes/esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6052:6052/tcp
      - 5353:5353/udp
