version: '3.7'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /mnt/docker-volumes/flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 5005
      published: 5005
      mode: host
    environment:
      - PASSWORD=!!!CENSORED!!!
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.flame-secure.rule=Host(`flame.louis45.de`)"
      - "traefik.http.routers.flame-secure.entrypoints=websecure"
      - "traefik.http.routers.flame-secure.tls=true"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true