version: '3.7'
services:
  flame:
    image: ghcr.io/fdarveau/flame:latest
    container_name: flame
    volumes:
      - /mnt/docker-volumes/flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 5005
      published: 5005
      mode: ingress
    environment:
      - PASSWORD=!!!CENSORED!!!
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flame.rule=Host(`flame.louisa.uno`)"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
