version: '3.7'
services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /mnt/docker-volumes/flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 5005
      published: 5005
      protocol: tcp
      mode: host
    environment:
      - PASSWORD=!!!CENSORED!!!
    restart: unless-stopped
