version: "3.7"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TZ=Europe/Berlin
    restart: always
    volumes:
      - /mnt/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - target: 3000
      published: 3000
      mode: ingress
    - target: 22
      published: 222
      mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.louisa.uno`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
