version: "3.7"
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - /mnt/docker-volumes/n8n:/home/node/.n8n
    ports:
    - target: 5678
      published: 5678
      protocol: tcp
      mode: host
    restart: unless-stopped
