version: "3.7"
services:
  n8n:
    image: n8nio/n8n
    volumes:
      - /mnt/docker-volumes/n8n:/home/node/.n8n
    ports:
    - target: 5678
      published: 5678
      protocol: tcp
      mode: ingress
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.louisa.uno`)"
      restart: unless-stopped
      networks:
        - traefik-public
networks:
  traefik-public:
    external: true
