version: "3.7"
services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
    - target: 3306
      published: 3309
      protocol: tcp
      mode: host
    volumes:
      - /mnt/docker-volumes/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!!!CENSORED!!!
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
    - target: 80
      published: 980
      protocol: tcp
      mode: host
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: unless-stopped
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.178.188:3309
  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: unless-stopped
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.178.188:3309
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-app