version: "3.7"
services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
    - target: 3306
      published: 3309
      mode: host
    volumes:
      - /mnt/docker-volumes/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!!!CENSORED!!!
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    ports:
    - target: 80
      published: 980
      mode: host
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /mnt/docker-volumes/nextcloud-cron/www-data:/var/spool/cron/crontabs/www-data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: unless-stopped
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.178.188:3309
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=102400M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.louis45.de`)"
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.tls=true"
    networks:
      - traefik-public
  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /mnt/docker-volumes/nextcloud-cron/www-data:/var/spool/cron/crontabs/www-data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: unless-stopped
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.178.188:3309
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-app
networks:
  traefik-public:
    external: true
