version: "3.7"
services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
    - target: 3306
      published: 3309
      mode: host
    volumes:
      - /mnt/docker-volumes/nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!!!CENSORED!!!
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
  nextcloud-app:
    image: nextcloud
    ports:
    - target: 80
      published: 980
      mode: ingress
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /mnt/docker-volumes/nextcloud-cron/www-data:/var/spool/cron/crontabs/www-data
      - /mnt/docker-volumes/nextcloud-config-mount/tweak.ini:/usr/local/etc/php/conf.d/tweak.ini:ro
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: always
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.1.188:3309
      - PHP_MEMORY_LIMIT=8192M
      - PHP_UPLOAD_LIMIT=102400M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.louisa.uno`)||Host(`nextcloud.louis45.de`)"
    networks:
      - traefik-public
    depends_on:
      - db
  nextcloud-cron:
    image: nextcloud
    volumes:
      - /mnt/docker-volumes/nextcloud-config:/var/www/html
      - /mnt/docker-volumes/nextcloud-cron/www-data:/var/spool/cron/crontabs/www-data
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud
      - type: tmpfs
        target: /tmp
    restart: always
    links:
      - db
    environment:
      - MYSQL_PASSWORD=!!!CENSORED!!!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=192.168.1.188:3309
    entrypoint: /cron.sh
    depends_on:
      - db
      - nextcloud-app
networks:
  traefik-public:
    external: true
