version: '3.7'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/docker-volumes/nginx-proxy-manager-data:/data
      - /mnt/docker-volumes/nginx-proxy-manager-letsencrypt:/etc/letsencrypt
