version: '3.7'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
    - target: 443
      published: 443
      protocol: tcp
      mode: host
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    - target: 81
      published: 81
      protocol: tcp
      mode: host
    volumes:
      - /mnt/docker-volumes/nginx-proxy-manager-data:/data
      - /mnt/docker-volumes/nginx-proxy-manager-letsencrypt:/etc/letsencrypt
