version: '3.7'
services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
      - target: 3000
        published: 3039
        mode: ingress
    image: openspeedtest/latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.louisa.uno`)"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
