version: '3.3'
services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
        - target: 3000
          published: 3039
          protocol: tcp
          mode: host
        image: openspeedtest/latest
