version: '3.7'
services:
  restreamer:
    image: datarhei/restreamer:cuda-latest
    container_name: restreamer
    restart: always
    volumes:
      - /mnt/docker-volumes/restreamer-config:/core/config
      - /mnt/docker-volumes/restreamer-data:/core/data
    ports:
    - target: 8080
      published: 7080
      mode: host
    - target: 8181
      published: 8181
      mode: host
    - target: 1935
      published: 1935
      mode: host
    - target: 1936
      published: 1936
      mode: host
    - target: 6000
      published: 6000
      protocol: udp
      mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.adguard-secure.rule=Host(`restreamer.louis45.de`)"
      - "traefik.http.routers.adguard-secure.entrypoints=websecure"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.services.adguard-secure.loadbalancer.server.port=8080"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
