version: '3.7'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    network_mode: bridge
    ports:
      - 4444:4444
    volumes:
      - /mnt/docker-volumes/selenoid-config:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    links:
      - selenoid
    ports:
    - target: 8080
      published: 4445
      protocol: tcp
      mode: host
    command: ["--selenoid-uri", "http://selenoid:4444"]
