version: "3.7"
services:
  sonarr:
    image: linuxserver/sonarr
    user: 0:0
    depends_on:
      - jackett
      - qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - UMASK_SET=0777
    volumes:
      - /mnt/docker-volumes/sonarr-config:/config
      - /mnt/nextcloud/louis/files/Medien/Serien:/tv
      - /mnt/nextcloud/louis/files/Downloads:/downloads
    ports:
    - target: 8989
      published: 8989
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    user: 0:0
    depends_on:
      - jackett
      - qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - UMASK_SET=0777
    volumes:
      - /mnt/docker-volumes/radarr-config:/config
      - /mnt/nextcloud/louis/files/Medien/Filme:/movies
      - /mnt/nextcloud/louis/files/Downloads:/downloads
    ports:
    - target: 7878
      published: 7878
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true
    volumes:
      - /mnt/docker-volumes/jackett-config:/config
      - /mnt/docker-volumes/jackett-downloads:/downloads
    ports:
    - target: 9117
      published: 9117
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8080
    volumes:
      - /mnt/docker-volumes/qbittorrent-config:/config
      - /mnt/nextcloud/louis/files/Downloads:/downloads
    ports:
    - target: 8080
      published: 8080
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.louisa.uno`)"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
    networks:
      - traefik-public
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr
    depends_on:
      - sonarr
      - radarr
      - jellyfin
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Berlin
    ports:
    - target: 5055
      published: 5055
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.louisa.uno`)"
    networks:
      - traefik-public
    volumes:
      - /mnt/docker-volumes/jellyseerr-config:/app/config
      - /mnt/docker-volumes/jellyseerr-config/resolv.conf:/etc/resolv.conf:ro
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/bazarr-config:/config
      - /mnt/nextcloud/louis/files/Medien/Filme:/movies
      - /mnt/nextcloud/louis/files/Medien/Serien:/tv
    ports:
    - target: 6767
      published: 6767
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  tdarr:
    image: ghcr.io/haveagitgat/tdarr
    ports:
    - target: 8265
      published: 8265
      mode: ingress
    - target: 8266
      published: 8266
      mode: host
    - target: 8267
      published: 8267
      mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tdarr.rule=Host(`tdarr.louisa.uno`)"
    networks:
      - traefik-public
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - UMASK_SET=002
      - serverIP=192.168.1.188
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=InternalNode
    volumes:
      - /mnt/docker-volumes/tdarr-server:/app/server
      - /mnt/docker-volumes/tdarr-configs:/app/configs
      - /mnt/docker-volumes/tdarr-logs:/app/logs
      - /mnt/docker-volumes/tdarr-media:/media
      - /tdarr-temp:/temp
      - /mnt/nextcloud/louis/files/Medien/Filme:/home/Tdarr/Media/Movies
      - /mnt/nextcloud/louis/files/Medien/Serien:/home/Tdarr/Media/TVShows
      - /mnt/nextcloud/louis/files/Fotos:/home/Tdarr/Media/Nextcloud/Fotos
      - /mnt/nextcloud/louis/files/InstantUpload:/home/Tdarr/Media/Nextcloud/InstantUpload
      - /mnt/nextcloud/louis/files/Medien/Tdarr-Samples:/app/server/Tdarr/Samples
    restart: unless-stopped
  readarr:
    image: linuxserver/readarr:develop
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/readarr-config:/config
      - /mnt/nextcloud/louis/files/Medien/Bücher:/books
      - /mnt/nextcloud/louis/files/Medien/Hörbücher:/spokenBooks
      - /mnt/nextcloud/louis/files/Downloads:/downloads
    ports:
    - target: 8787
      published: 8787
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.readarr.rule=Host(`readarr.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    volumes:
      - /mnt/docker-volumes/jellyfin-config:/config
      - /mnt/docker-volumes/jellyfin-cache:/cache
      - /mnt/nextcloud/louis/files/Medien:/media
    ports:
    - target: 8096
      published: 8096
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
  kavita:
    image: kizaing/kavita
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - /mnt/docker-volumes/kativa-config:/kavita/config
      - /mnt/nextcloud/louis/files/Medien/Bücher:/books
    ports:
    - target: 5000
      published: 5000
      mode: ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`kavita.louisa.uno`)"
    networks:
      - traefik-public
    restart: unless-stopped
networks:
  traefik-public:
    external: true
