version: '3.7'
services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/certs/dynamic_conf.yml"
    ports:
    - target: 443
      published: 443
      mode: host
    - target: 80
      published: 80
      mode: host
    - target: 8080
      published: 81
      mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-volumes/traefik-certs:/certs
    restart: unless-stopped
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
