version: "3.8"
services:
  web:
    build: .
    image: mrbrax/twitchautomator:master
    ports:
      - "8082:8080"
    volumes:
      - /mnt/docker-volumes/twitchautomator-data:/usr/local/share/twitchautomator/data
      - /mnt/nextcloud/louis/files/Medien/Twitchautomator:/data/storage
    environment:
      - NODE_ENV=production
      - TCD_ENABLE_FILES_API=0
      - TCD_EXPOSE_LOGS_TO_PUBLIC=0
      - TCD_MIGRATE_OLD_VOD_JSON=0
      - BASE_URL=http://192.168.178.188
