version: '3.7'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /mnt/docker-volumes/uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 3001
      published: 3001
      mode: host
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.louis45.de`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true