version: '3.7'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /mnt/docker-volumes/uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - target: 3001
      published: 3001
      mode: host
    restart: always
