version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zF64ZdXxZNhCum282UZQZK3yZ9RcSgxr
      MYSQL_DATABASE: vrc-avatars
      MYSQL_TCP_PORT: 53306
      MYSQL_UNIX_PORT: 53306
    volumes:
     - /mnt/docker-volumes/vrc-avatar-db-mysql:/var/lib/mysql
    ports:
    - target: 53306
      published: 53306
      mode: host
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
    - db
    links:
      - db
    environment:
    - PMA_HOST=192.168.178.188
    - PMA_PORT=53306
    - PMA_ARBITRARY= 1
    restart: always
    ports:
    - target: 80
      published: 58080
      mode: host
